baseURL: "https://feilinhan.github.io" 
title: Feilin Han
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Profile
          url: profile
          weight: 2
        - name: Publications
          url: papers
          weight: 3
        - name: Projects
          url: projects
          weight: 4 
        - name: Teaching
          url: teaching
          weight: 5
        - name: People
          url: people
          weight: 6

params:
    description: "I am a Lecturer (~Assistant Professor) at Beijing Film Academy, China. My research focuses on Digital Film and Multimedia Technology."
    # author: Feilin Han
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Han Feilin (韩菲琳)
          subtitle: "Hi! I am a Lecturer (Assistant Professor) in the Department of Film and TV Technology at Beijing Film Academy, China. 
          Currently, I am a visiting scholar at the school of Art, Design and Media, Nanyang Technological University, Singapore, 
          co-working with [**Prof. Benjamin Seide**](http://www.ataribaby.de/).
          I am also a Master's Supervisor in **Digital Film Technology** and **Generative AI in Film Production** at BFA. 
          
          <br><br>
          My research focuses on **AI**, **Computer Vision**, **Virtual Reality** and **Human-AI Interaction** in Digital Film Production.
          I am also interested in Cinematic Virtual Reality (Cinematography in VR, VR Filmmaking, VR Storytelling), 
          VFX in Filmmaking (Motion Capture, Digital Double, Digital Asset Management), 
          and AI-Generated Content (AIGC) in Digital Art. 

          <br><br>
          With an **interdisplinary background**, 
          I studies at the School of Theater, Film, and Television, UCLA, in 2011, 
          worked as a research assistant in the Department of Computer Science at National Tsing Hua University, in 2013,
          and was a Marie Curie Research Scholar in the National Centre for Computer Animation, UK, in 2016.

          <br><br>
          I am a **Researcher**, **Technical Director**, and **Designer**, exploring **immersion** and **perception**."

          imageUrl: "Fiona_2024.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Feilin Han
          buttons:
            - name: Profile
              url: profile
            - name: Publications
              url: papers
            - name: Projects
              url: projects
            - name: Teaching
              url: teaching
            - name: People
              url: people

            

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=3igxYUQAAAAJ&hl=en&oi=ao
        - name: Linkedin
          url: https://sg.linkedin.com/in/fionafffff
        - name: YouTube
          url: https://www.youtube.com/@fionahan9994
        - name: Instagram
          url: https://www.instagram.com/fionaisgood_/
        


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Home"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

